### PR TITLE
Create SJET-AOCODARC_F405V3_SD.config

### PR DESCRIPTION
**Pull request by ChenYang78256**
1.Serial port 1 Use GPS
2.Serial port 2 Use a receiver
3.The features of LED_STRIP、OSD、GPS are enabled by default
4.The default GPS protocol is ublox by default
5.The receiver selects CRSF protocol by default
6.The default motor protocol is Dshot600 by default 
7.Bluetooth and 9v switches are enabled by default
8. Use the User1 and User2 mode，User3 mode
9.Add User3 mode. User3 mode Controls the switchover between cam1 and cam2 
10.Replace flash with sd card

### CODE REVIEW

**Comment by ChenYang78256** [comment]
Because the target board is being repaired, it has not been self-tested

**Comment by lida2003** [comment]
> Because the target board is being repaired, it has not been self-tested

OK, We'll find way to solve this today. Anyway, we need to verify these configurations.

Please change file name to "SJET-AOCODARC_F405V3_SD.config" 

PS: We'll use naming rule "SJET-AOCODARC_F405V3.config" for Flash verson, and "SJET-AOCODARC_F405V3_SD.config"  for SDCard version

**Comment by ChenYang78256** [comment]
The filename has been changed.

**Comment by ChenYang78256** [comment]
F405V3 SD V3 self test passed.

**Pull request merged**
